apiVersion: v1
kind: Pod
metadata:
  name: plotnetcfg-debug
  labels:
    app: plotnetcfg-debug
spec:
#  nodeName:
  containers:
  - command: ["/bin/bash"]
    args: ["/dump-plotnetcfg.sh"]
    image: rbbratta/plotnetcfg-debug:fedora31
    imagePullPolicy: Always
    name: plotnetcfg-debug
    resources: {}
    securityContext:
      privileged: true
      runAsUser: 0
    stdin: true
    stdinOnce: true
    tty: true
  hostNetwork: true
  hostPID: true
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
